### ISSUE TITLE
BETA Road Map / remaining issues

### ISSUE THREAD

**Issue by machty** [FutureProofRetail/zen-engine-ruby#2]
## Remaining issues until beta-ready

I believe the implementation is mostly there but there are still a few pretty major open issues:

- [x] most executions still fail with double-free pointer exception; I believe this is a quick FFI thing to file, perhaps related to the string that we return from the load callback
- [x] release cross-platform gem
- [ ] do some kind of leak/memory/valgrind test to make sure we're not leak either on the native or Ruby side
- [ ] add a number of error condition testing; wouldn't want to trigger unhandled panics in response to poorly formatted data
- [ ] implement support for custom node handlers
